#include<iostream.h>
#include<conio.h>
#include<dos.h>
#include<stdlib.h>
void welcome (void);
void load()
{
 r l=178;
  int per ,k;
 cout<<"\n\n\n\n\n\n\n\n\t     NOW LOADING.............................\n\t\t\t";
 for( k=1;k=10;k++)
 {  or( k=10;k<30;k++)
 {
  cout<<l;
  delay(200);
 }
it(0);
}
void welcome()
{
 cout<< "\n\n\n\n\n\n\t\tWELCOME TO INTERACTIVE TELIPHONE DIRECTORY";
 //if(getch())
 //exit(0);
  main()
{
 clrscr();
 welcome();
 getch();
}